// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx_FAlzTC5t-XWmYEuI5MMRGLk7tXHygk',
    appId: '1:1057474142828:web:972569b324011af529ae49',
    messagingSenderId: '1057474142828',
    projectId: 'savorysync-1b531',
    authDomain: 'savorysync-1b531.firebaseapp.com',
    storageBucket: 'savorysync-1b531.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz62QqqA18FOCmIbdWr9i4jj0RJEG0wtk',
    appId: '1:1057474142828:android:db1b8093b2e98e7229ae49',
    messagingSenderId: '1057474142828',
    projectId: 'savorysync-1b531',
    storageBucket: 'savorysync-1b531.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrx0ltGE1fjt1M6iIHUSpxaMAEqUbWcf4',
    appId: '1:1057474142828:ios:33e6d7f4355661db29ae49',
    messagingSenderId: '1057474142828',
    projectId: 'savorysync-1b531',
    storageBucket: 'savorysync-1b531.firebasestorage.app',
    iosBundleId: 'com.example.savorysync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrx0ltGE1fjt1M6iIHUSpxaMAEqUbWcf4',
    appId: '1:1057474142828:ios:33e6d7f4355661db29ae49',
    messagingSenderId: '1057474142828',
    projectId: 'savorysync-1b531',
    storageBucket: 'savorysync-1b531.firebasestorage.app',
    iosBundleId: 'com.example.savorysync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx_FAlzTC5t-XWmYEuI5MMRGLk7tXHygk',
    appId: '1:1057474142828:web:201ee20fdbb5942c29ae49',
    messagingSenderId: '1057474142828',
    projectId: 'savorysync-1b531',
    authDomain: 'savorysync-1b531.firebaseapp.com',
    storageBucket: 'savorysync-1b531.firebasestorage.app',
  );
}
